---
threshold: 98
require_exact_threshold: false
path: ['acceptance/helpers/*.rb','lib/**/*.rb','modules/ref_arch_setup/tasks/*.rb','spec/**/*.rb']
rules:
  ApiTag::Presence:
    enabled: false
  ApiTag::Inclusion:
    enabled: false
  ApiTag::ProtectedMethod:
    enabled: false
  ApiTag::PrivateMethod:
    enabled: false
  Summary::Length:
    enabled: false
  Summary::SingleLine:
    enabled: false
