version: '3.6'

services:
  controller:
    build:
      context: .
      target: ${RAS_TARGET}
    image: ras/${RAS_TARGET}
    volumes:
      - '~/.ssh:/root/.ssh'

  master:
    build:
      context: .
      target: base
    image: ras/base
    volumes:
      - '~/.ssh:/root/.ssh'
